### ISSUE TITLE
"当前人数过多，请等待5分钟后尝试"

### ISSUE THREAD

**Issue by keenkn** [bear-zd/ChaoXingReserveSeat#14]
老哥还更新吗，我也是shu的。为什么我在网页端学习通没办法打开座位预约那个界面

**Comment by bear-zd** [comment]
我这边测试倒是没异常，可以提供更详细的信息吗？比如说是哪个页面打不开

**Comment by keenkn** [comment]
老哥谢谢你，我刚才解决这个问题了，已经测试成功了。打不开的页面是：我登陆网页版的学习通，找不到“座位预约”这个选项。不过老哥你也直接给出了四楼和五楼的编号，暂时没有其他问题了。多谢！



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bear-zd/ChaoXingReserveSeat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月19日(星期天) 中午1:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bear-zd/ChaoXingReserveSeat] "当前人数过多，请等待5分钟后尝试" (Issue #14)





 
我这边测试倒是没异常，可以提供更详细的信息吗？比如说是哪个页面打不开
