### ISSUE TITLE
rebuid分支问题

### ISSUE THREAD

**Issue by wulala123wu** [bear-zd/ChaoXingReserveSeat#15]
预约的座位号总是我设置的座位号的第一个数字，比如我设置600，预约的却是6。而且我不管怎么设置，好像只能预约明天。

**Comment by bear-zd** [comment]
rebuild分支的预约逻辑有点问题，我之后改一下

**Comment by bear-zd** [comment]
rebuild的新commit尝试解决这个问题了，在main.py中将第17行的：RESERVE_NEXT_DAY改为True即可。

**Comment by wulala123wu** [comment]
开启滑块验证后就会报错
func_dict[args.method](usersdata, args.action) 
14 File "/home/runner/work/xxtlibrary/xxtlibrary/main.py", line 61, in main 
15 if sum(success_list) == today_reservation_num: 
16    ^^^^^^^^^^^
17TypeError: 'NoneType' object is not iterable 
18An error occurred: Expecting value: line 1 column 1 (char 0)

**Comment by wulala123wu** [comment]
而且预约还是会约座位号的第一个数字，但好像只有在预约明后天的情况下会出现

**Comment by bear-zd** [comment]
因为没有账号测试和详细的信息所以找不到出问题的地方，我提交了一版带日志的，可以提供详细日志。或者方便的话可以微信联系我

**Comment by wulala123wu** [comment]
好的 vx:w159326082

**Comment by bear-zd** [comment]
滑块验证仍然存在问题，后续可能继续改改了

**Comment by bear-zd** [comment]
现在本项目支持滑块验证和正常抢座，目前主分支为rebuild分支，如有异常请在此提出，同时旧版在main分支下，如果只需要简单的需求可以直接使用之前main分支下的代码（但是由于js2py依赖所以不支持3.12）
