### ISSUE TITLE
当前使用人数较多

### ISSUE THREAD

**Issue by XuejiFang** [bear-zd/ChaoXingReserveSeat#2]
{'msg': '当前使用人数较多，请5分钟后再次尝试提交！', 'success': False}
请问这个报错是什么原因呢？
我记得之前用这个脚本的时候，没有遇到过这种情况。

**Comment by bear-zd** [comment]
之前我也没遇到过这种情况，可能就是脚本运行时预约人数过多导致的？
请问这种情况是只出现过一次还是频繁出现？

**Comment by XuejiFang** [comment]
我好久没用了，今天第一次用，就出现这个情况。
预约人数过多，是指约同一个位置人太多了吗，有很多人同时在刷这个位置吗？
但是，我选了很多位置，在遍历，每一个位置都是这么显示的`{"msg":"当前使用人数较多，请5分钟后再次尝试提交！","success":false}`。

**Comment by bear-zd** [comment]
有可能是短时间内的请求数量太多导致的，我检查一下

**Comment by bear-zd** [comment]
查到原因了，学习通座位预约更新了一个新的字段enc，在登陆后在选座界面F12搜索`enc: submitVerify.verifyParam(paramObj)` 即可看到新字段的获取方式，目前尝试能否用python模仿函数
https://office.chaoxing.com/front/third/apps/seat/code?id=5483&seatNum=002

**Comment by XuejiFang** [comment]
加油[(*•̀ㅂ•́)و]

**Comment by bear-zd** [comment]
暂时解决了：bebdad187fa1a3f6ec6014f9068f09f064a01781
