### ISSUE TITLE
UnboundLocalError: cannot access local variable 'usernames' where it is not associated with a value

### ISSUE THREAD

**Issue by LuG3Zz** [bear-zd/ChaoXingReserveSeat#20]
![图片](https://github.com/bear-zd/ChaoXingReserveSeat/assets/52660939/822ca755-3926-46bb-a59b-cfc5a585787a)

**Comment by bear-zd** [comment]
please fetch the new version and retry.

**Comment by LuG3Zz** [comment]
> please fetch the new version and retry.

Thank you！！

**Comment by LuG3Zz** [comment]
kkkL
