### ISSUE TITLE
启动时会有数秒的延迟导致抢座失败

### ISSUE THREAD

**Issue by Akonsting** [bear-zd/ChaoXingReserveSeat#25]
我在windows系统里设置的计划任务是18:00:00运行脚本，但是脚本输出上显示start time是18:00:02，这让我的座位被别人抢掉了，请问该怎么解决？

**Comment by bear-zd** [comment]
因为登陆等操作还是需要一点时间的，你把计划任务往前设置1分钟或者2～3s让它提前开始试试

**Comment by Akonsting** [comment]
> 因为登陆等操作还是需要一点时间的，你把计划任务往前设置1分钟或者2～3s让它提前开始试试

如果设置的开始时间太早会不会超过最大尝试次数而失败？

**Comment by bear-zd** [comment]
把最大尝试次数也调大一点应该不会有太大问题

**Comment by Akonsting** [comment]
> 把最大尝试次数也调大一点应该不会有太大问题

OK，感谢。
