### ISSUE TITLE
json读取

### ISSUE THREAD

**Issue by stupchen** [bear-zd/ChaoXingReserveSeat#28]
我们学校最大一次预约不得超过四小时，但是可以预约多次达到一天，所以我在修改的时候增加了多个字典，除了时间段不一样其他都一样，运行的时候只读取了字典的第一项

**Comment by bear-zd** [comment]
所以没有其他问题？

**Comment by stupchen** [comment]
其他的没有了，主要就是json中的三段只执行第一段。
其他的我在主函数入口做了一个优化，用一个while死循环去判断是否到达预约开放时间，而不是每次去尝试去预约座位，每次尝试间隔0.2秒相对于获取当前时间会慢上一点。
