### ISSUE TITLE
关于旋转滑块验证

### ISSUE THREAD

**Issue by qwertyuiop-abc** [bear-zd/ChaoXingReserveSeat#29]
作者大佬，我们学校的图书馆预约需要的滑块验证是旋转型的，可以用吗
![image](https://github.com/user-attachments/assets/84d11a36-7fc1-4a8b-bb74-73c9b9d25e6b)

**Comment by bear-zd** [comment]
不能用，没有写旋转滑块匹配的相关代码，如果感兴趣的话可以自己实现
