### ISSUE TITLE
{'msg': '验证失败，请重新验证', 'success': False}

### ISSUE THREAD

**Issue by xiexie30** [bear-zd/ChaoXingReserveSeat#3]
您好，我出现以下问题，核对过roomID和seatID，请问怎么解决？
{'roomId': '3789', 'day': '2023-10-28', 'startTime': '20:00', 'endTime': '21:00', 'seatNum': '006', 'token': 'a09ca81452d14d9c99e94cc3246f4b33', 'captcha': '', 'type': 1, 'verifyData': 1, 'enc': 'cae327362be3c438dc0e622cf223120a'}
{'msg': '验证失败，请重新验证', 'success': False}

**Comment by bear-zd** [comment]
测试了一下，大致了解情况了。试图访问了一下你的学校图书馆应用，提示“该应用只允许本单位用户使用”，可能你的学校还加了一些相关的验证。如果调试的话可能需要一些账号信息或者抓包获取的信息

**Comment by xiexie30** [comment]
怎么提供信息呢

**Comment by bear-zd** [comment]
可以加我微信：Bear_zidea

**Comment by bear-zd** [comment]
分析了一下，该错误是由于滑块验证没通过导致的（有些学校会有滑块验证系统），可能需要一定的特殊处理，代价就是抢座性能会下降挺多。我慢慢推进该工作。

**Comment by bear-zd** [comment]
Closes #4
