### ISSUE TITLE
日期问题

### ISSUE THREAD

**Issue by 03hqy0v0** [bear-zd/ChaoXingReserveSeat#30]
使用Actions的时候是否会由于UTC时间问题出现日期与当天日期不同的情况呢？

**Comment by bear-zd** [comment]
会出现的，所以代码里面当action为True时会时间+8来修正时区

**Comment by 03hqy0v0** [comment]
感谢学长，还有个问题，就是Github Actions Schedule定时启动的时间不准确怎么办呢，比如定时7:00整，实际运行时会延迟5-20分钟时间不等怎么办呢

**Comment by bear-zd** [comment]
修改一下.github/workflows/reserve.yml第9行的cron时间提前一点即可。现在的含义是：
59：分钟部分，表示在每小时的第59分钟。
21：小时部分，表示在每天的21点（即晚上9点）。
*：日部分，表示每一天。
*：月部分，表示每一月。
0,1,2,3,4：周几部分，表示每周的星期日、星期一、星期二、星期三和星期四。
由于时差导致实际上action的cron时间要-8小时，如果想要提前的话修改小时部分往前一点即可（由于github action可能会出现某个时间使用人数过多而导致延迟排队等问题）
