### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by GccEzz** [bear-zd/ChaoXingReserveSeat#31]
大佬您好想请教一下如何修改能约次日的座位呀？我将RESERVE_NEXT_DAY = True 修改为True但是还是约的当天的座位，只有过凌晨十二点才能约，而我们学校图书馆预约次日的时间是前一天的晚上七点钟开始。
- INFO - {'msg': '该时间段已过，不可预约！', 'success': False}
submit parameter {'roomId': '5948', 'startTime': '21:00', 'endTime': '22:00', 'day': '2024-09-02', 'seatNum': '030', 'captcha': '', 'token': '6ed59c94f57c40b79068b31615c41c1a'}

**Comment by bear-zd** [comment]
如果没理解错的话你这个是需要在前一天7点启动预约脚本然后预约第二天的座位是吗？这样的话修改一下END_TIME = 19:01:00 然后让脚本在大概18:59:00左右开始运行就好了

**Comment by GccEzz** [comment]
> 如果没理解错的话你这个是需要在前一天7点启动预约脚本然后预约第二天的座位是吗？这样的话修改一下END_TIME = 19:01:00 然后让脚本在大概18:59:00左右开始运行就好了

感谢回复！对，我们学校是前一天晚上七点约第二天的，我昨天晚上想测试一下约今天的座位，但是他告诉我该时间段已过，说明它约的还是昨天当天的座位，我今天试试修改为19：01让他自动运行，看能不能约到明天的。还想问一下您，如果我们学校限制单次预约时长为6小时，该在config.json里面如何修改呀？

**Comment by bear-zd** [comment]
在config.json中time的值修改一下，范围之间时间长度不超过6h即可（比如 `"time": ["08:00","14:00"],`），更加具体的情况就看你的需求了

**Comment by GccEzz** [comment]
请问一下我下面这个报错的原因是什么呀？我今天中午设置了两个时间段，一个"time": ["10:00", "16:00"],和一个"time": ["16:00", "22:00"],写在两个花括号里。但是它今天给我提示了这个2024-09-03 19:00:59,833 - INFO - submit parameter {'roomId': '5950', 'startTime': '10:00', 'endTime': '16:00', 'day': '2024-09-04', 'seatNum': '0', 'captcha': '', 'token': '87289a7714f2403cbdc0ee89694ad31a'}
2024-09-03 19:00:59,876 - INFO - {'msg': '非法预约', 'success': False}
2024-09-03 19:01:00,077 - INFO - Today not set to reserve是因为我的config格式问题嘛

**Comment by bear-zd** [comment]
seatNum填错了，请仔细看一下readme，seatNum要补全到3位的

**Comment by GccEzz** [comment]
我用0补全至三位数了呀，这里的seatid是seatNum嘛，名字要改吗？
        "time": ["08:00","09:00"],
        "roomid":"5948", 
        "seatid":"058", 
        "daysofweek": ["Monday" , "Tuesday", "Wednesday", "Thursday", "Friday"]
        },我用python main.py -m debug运行可以正确获取到座位号2024-09-03 23:34:20,431 - INFO - Captcha token 
2024-09-03 23:34:20,431 - INFO - submit parameter {'roomId': '5948', 'startTime': '08:00', 'endTime': '09:00', 'day': '2024-09-03', 'seatNum': '058', 'captcha': '', 'token': '143bb270461c43af974f3511b5b391c9'}
2024-09-03 23:34:20,522 - INFO - {'msg': '该时间段已过，不可预约！', 'success': False}
但是用python main.py -m reserve运行就显示2024-09-03 23:34:52,349 - INFO - submit parameter {'roomId': '5948', 'startTime': '08:00', 'endTime': '09:00', 'day': '2024-09-04', 'seatNum': '0', 'captcha': '', 'token': 'd45c4443b2c44c259238d90e3033d579'}
2024-09-03 23:34:52,429 - INFO - {'msg': '非法预约', 'success': False}不知道为什么座位号没有正确传入

**Comment by GccEzz** [comment]
我好像发现问题了，好像是上面的花括号里seatid这个对象的数组没加括号[]导致传入失败，想请问一下您如果我想同时预约两个时间段，因为每个时间段不超过六小时，比如我想约次日的10:00到16：00和16:00到22:00应该如何修改config.json的格式呢？是否需要修改main.py里面的login_and_reserve函数呢？因为我前面修改了config结果日志提示我参数传入过多

**Comment by bear-zd** [comment]
如果不想麻烦的话就吧config文件再拷贝一份，修改一下预约时间，先后运行python main.py -c config1.json; python main.py -c config2.json

**Comment by GccEzz** [comment]
> 如果不想麻烦的话就吧config文件再拷贝一份，修改一下预约时间，先后运行python main.py -c config1.json; python main.py -c config2.json

感谢，今天成功了。我是直接再config里面又copy了一下那个格式
