### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by slawgut** [bear-zd/ChaoXingReserveSeat#32]
访问电脑端不显示时间表怎么办呀，之前可以的，这学期用不了了

**Comment by bear-zd** [comment]
不太理解是什么问题，有更详细的描述、日志或者截图吗

**Comment by slawgut** [comment]
![image](https://github.com/user-attachments/assets/686c5919-06f7-40eb-b3f7-c7e317c75cb6)

**Comment by slawgut** [comment]
![image](https://github.com/user-attachments/assets/921ff088-e4ca-4b59-a40f-02fb3bc972f3)

**Comment by slawgut** [comment]
解决了，谢谢学长
