### ISSUE TITLE
有关抢座速率问题

### ISSUE THREAD

**Issue by GccEzz** [bear-zd/ChaoXingReserveSeat#34]
学长您好，我还想问一下抢座的速率还能提升吗？因为这两天都没抢过别人，基本上座位一秒内就被抢了😭，我尝试用多线程虽然每次能同时提交多个时段的请求，但是好像只能有一个被处理，然后我又尝试用多线程来通过两个账号来抢，但这样好像也会出现冲突有时，不稳定

**Comment by bear-zd** [comment]
基本不能了，目前这套没有涉及到协程同时预约多个座位的相关工作，所以会受到一定限制。如果还想提高速率的话尝试提前运行，把SLEEP_TIME设置为0（不保证会不会被ban）

**Comment by GccEzz** [comment]
好的好的，谢谢了
