### ISSUE TITLE
请问如何解决enc验证的问题

### ISSUE THREAD

**Issue by JINAN-xxx** [bear-zd/ChaoXingReserveSeat#36]
目前最新的预约需要提交enc，请问大佬这块有什么比较好的解决思路么https://office.chaoxing.com/data/apps/seatengine/submit?roomId=1015&startTime=22%3A00&endTime=22%3A30&day=2024-09-11&captcha=&seatNum=098&token=95d1bb8cefc346e8888c3c131d367996&enc=9f4bc2804b1f693498ec969c765a38b6

**Comment by bear-zd** [comment]
提交enc指的是什么？是发送抢座请求时候的enc字段吗？这个我实现并放在[encrypt.py](https://github.com/bear-zd/ChaoXingReserveSeat/blob/rebuild/utils/encrypt.py)的enc函数中了
