### ISSUE TITLE
哥们儿 我准备搞个点选式验证码的破解 我想问你一下 你对服务器发送请求的几个参数都是什么意思 以及他的url你是怎么找到的 

### ISSUE THREAD

**Issue by tomgaveen** [bear-zd/ChaoXingReserveSeat#44]

**Comment by bear-zd** [comment]
就浏览器F12-网络（高级一点可以用fiddler），点击提交获得会得到对应的request和response（一般这个request部分字段需要增加一些加密或者时间戳，这里可以参考我的代码中的滑块解锁模块），获得图片本地处理之后可以得到对应的值（比如滑块就是滑块距离0点的x值提交到对应的url即可），之后可以获得一个captcha，配合着其他的参数传入加密函数即可
大致就是这个流程，不过由于不同学校的提交链接、请求头、跨域都有所不同可能需要尝试自己抓取或解决了，有问题可以在issue上多交流
