### ISSUE TITLE
滑块解锁NonetypeError 把c_captcha_headers里面的host的captha-c改为captha-b

### ISSUE THREAD

**Issue by tomgaveen** [bear-zd/ChaoXingReserveSeat#46]

**Comment by bear-zd** [comment]
由于我这边没有滑块验证的测试账号所以不知道这个c_captcha_headers是不是通用解决方案，不管怎么说先留着这个issue，如果可以解决的话我就尝试更新代码了

**Comment by bear-zd** [comment]
如果可以的话可以提供更加详细的说明吗？ @tomgaveen

**Comment by tomgaveen** [comment]
他们的host主机改名字了改成
captha-b了 所以读取不到图像了
