### ISSUE TITLE
哥们能帮我看下这个问题嘛，还没看到回复，问题被删了

### ISSUE THREAD

**Issue by mfornothing** [bear-zd/ChaoXingReserveSeat#49]
[new.txt](https://github.com/user-attachments/files/17178344/new.txt)

**Comment by bear-zd** [comment]
页面token有问题，说明你们学校图书馆的token抓取链接（或者说预约链接不是https://office.chaoxing.com/front/third/apps/seat/code  ） ，这个需要搞清楚学校的预约和提交链接是什么，具体参考一下ext分支的：`utils/huangshan_customed_reserve.py`和`utils/customed_reserve.py`，里面提供了两个其他学校的预约链接，具体的修改方案还得自己抓取并稍微修改一下

**Comment by mfornothing** [comment]
> 页面token有问题，说明你们学校图书馆的token抓取链接（或者说预约链接不是https://office.chaoxing.com/front/third/apps/seat/code ） ，这个需要搞清楚学校的预约和提交链接是什么，具体参考一下ext分支的：`utils/huangshan_customed_reserve.py`和`utils/customed_reserve.py`，里面提供了两个其他学校的预约链接，具体的修改方案还得自己抓取并稍微修改一下

好的谢谢了

**Comment by tomgaveen** [comment]
哥们儿 我好像又知道了 这个问题只要把所有的url的seat 改为seatengine就行了 哈哈哈哈 这代码都被我摸透了

**Comment by tomgaveen** [comment]
因为学校分考研的和不考研的 所以就有两种位置之分

**Comment by tomgaveen** [comment]
哥们儿 你哪个学校的

**Comment by tomgaveen** [comment]
武汉的吗？
