### ISSUE TITLE
enc问题

### ISSUE THREAD

**Issue by JINAN-xxx** [bear-zd/ChaoXingReserveSeat#52]
请问大佬就是enc加密还可用么

**Comment by bear-zd** [comment]
应该还可用的

**Comment by JINAN-xxx** [comment]
我这边显示预约失败，是学校不一样所导致的么，能否联系你对这部分进行学习，谢谢你的回复

**Comment by bear-zd** [comment]
你把日志发一下看看，enc编码不会有太大问题，一般可能出现的问题在 选课网址不同 页面token获取方式不同 验证方式不同等，详细可以看：[wiki](https://github.com/bear-zd/ChaoXingReserveSeat/wiki/%E5%A6%82%E4%BD%95%E7%BC%96%E5%86%99%E8%87%AA%E5%AE%9A%E4%B9%89%E8%84%9A%E6%9C%AC%E9%80%82%E7%94%A8%E4%BA%8E%E8%87%AA%E5%B7%B1%E5%AD%A6%E6%A0%A1)

**Comment by JINAN-xxx** [comment]
![image](https://github.com/user-attachments/assets/99796180-6854-4118-a4cf-1d3f76850506)
我这边的日志信息是：当前使用人数较多，请5分钟后再次尝试提交！
此外，我对你的代码进行了修改，登录页面的接口没问题，问题应该是出在最后的enc加密部分，请问你这部分能支持更新么。

**Comment by bear-zd** [comment]
我试了一下，目前是可用的，感觉可能有以下几个原因：
1、encode方式不同，这个可能性不大，得抓包看一下，详细看submitVerify.js，我们学校是这个：
https://reserve.chaoxing.com/staticreserve/js/src/front/apps/common/enc/min/submitVerify.min.js?t=2024101221
因为js做了混淆所以难以恢复，得想办法解析回python或者依旧跟以前一样调用pyjs（我也抓包了一下你们学校的，貌似是相同）的）

2、请求里面缺了一些键值，比如我校提交的请求如下（从js里面直接复制过来的）：
```js
 {
        roomId: roomId,
        startTime: _this.chosedTimeInfo.startTime,
        endTime: _this.chosedTimeInfo.endTime,
        day: _this.chosedDay,
        captcha: _this.captcha,
        seatNum: _this.chosedSeatNum,
        token: '2c318f3a504e45628fce6fabbc69a9c9',
        enc: submitVerify.verifyParam(paramObj)
      }
```
我测试了一下你校预约（可能是因为设置了外校无法预约权限所以预约不上），键值确实有点不太相同：
```js
 operateData('data/apps/seat/submit', {
        roomId: roomId,
        day: _this.chosedDay,
        startTime: _this.chosedTimeInfo.startTime,
        endTime: _this.chosedTimeInfo.endTime,
        seatNum: _this.chosedSeatNum,
        captcha: _this.captcha,
        token: 'bec250dceee24479a63d31cea6895169',
        type: 1,//标识扫码预约（需要判断是否需要自动签到）
        verifyData: 1,
        enc: submitVerify.verifyParam(paramObj)
      }
```
只需要在`reserve.py`,`get_submit`函数里面的parm加上两个键值应该可以解决？
 ```python
 parm = {
            "roomId": roomid,
            "startTime": times[0],
            "endTime": times[1],
            "day": str(day),
            "seatNum": seatid,
            "captcha": captcha,
            "token": token,
            "type": "1",
            "verifyData": "1"
        }
```

**Comment by JINAN-xxx** [comment]
谢谢你的回复，我这边已成功，我重新检查了加密方式。
