### ISSUE TITLE
佬，这是什么问题啊

### ISSUE THREAD

**Issue by boostemotion** [bear-zd/ChaoXingReserveSeat#57]
![屏幕截图 2024-10-27 194825](https://github.com/user-attachments/assets/35c8c6d6-03a9-42ba-8e51-f53995eaec37)

**Comment by bear-zd** [comment]
密码里面有逗号，或者是密码没有放对地方？

**Comment by boostemotion** [comment]
![屏幕截图 2024-10-28 000026](https://github.com/user-attachments/assets/0bfa473e-b286-43d1-8da0-c7365f09474e)
是在这添加账号密码吧，密码没逗号呀

**Comment by bear-zd** [comment]
我看到你fork的代码了，config.json里面的预约数量是5个，但是在secrets里面你填的账号密码应该只有一个，把secrets里面账号和密码复制够5份就好了，用英文逗号隔开
