### ISSUE TITLE
请问关于如何获得deptIdEnc值的问题

### ISSUE THREAD

**Issue by csskrtao** [bear-zd/ChaoXingReserveSeat#58]
佬项目中有一个getroomid的方法应该是获取roomid的方法，我用python main.py -m room 去运行的时候获取roomid需要输入deptIdEnc，请问在不采取手动抓包的情况下，这个值是在哪里获取到的，想学习一下，希望各位佬友能解答一下   
```
https://office.chaoxing.com/data/apps/seat/room/list?cpage=1&pageSize=100&firstLevelName=&secondLevelName=&thirdLevelName=&deptIdEnc={encode}
```

**Comment by bear-zd** [comment]
正确的获取方式是断网的时候进入座位预约并复制链接就好了（在readme.md中列出来了）
deptIdEnc虽然是一个编码的值，但是考虑到其获取方式，可能是对于不同图书馆的相关id参数的一个硬编码，但是具体的获取方式。不同的图书馆deptIdEnc值不同但是一般不会变化，一个合理的可能是学习通存在某个接口可以进行查询，但是更加详细的还得需要抓包学习通app了

**Comment by csskrtao** [comment]
对，我就想问的是这个查询到接口应该是什么，佬当时写这个roomid这个方法是为了测试什么呀？

**Comment by bear-zd** [comment]
因为预约座位需要roomid（图书馆楼层/房间号），但是如果不抓包的话这个roomid获取方式是需要deptIdEnc，通过这个deptIdEnc向一个接口发送请求就可以得到这个deptIdEnc的所有roomid（应该是这样一个包含关系），所以写了get_roomid这个方法。
不过后面发现可以直接断网查到对应的roomid，所以这个就废弃不用了。

**Comment by csskrtao** [comment]
> 因为预约座位需要roomid（图书馆楼层/房间号），但是如果不抓包的话这个roomid获取方式是需要deptIdEnc，通过这个deptIdEnc向一个接口发送请求就可以得到这个deptIdEnc的所有roomid（应该是这样一个包含关系），所以写了get_roomid这个方法。 不过后面发现可以直接断网查到对应的roomid，所以这个就废弃不用了。

明白了，我也是好奇佬这么项目当时还特意添加了这个方法，后期却没怎么用到
