### ISSUE TITLE
学校用的套壳版本，作者可以处理一下吗

### ISSUE THREAD

**Issue by itmanmax** [bear-zd/ChaoXingReserveSeat#64]
我们学校的不是学习通上面的 是今日校园上面的，但是逻辑都是一样的，http://libwfw.ahnu.edu.cn/reserve/front/third/apps/seat/select?deptIdEnc=3c259958eb5103a7&id=10971&day=2024-12-29&backLevel=2&pageToken=f9c44e33fea9473ebd570be54921259e&fidEnc=3c259958eb5103a7  估计登录的地方需要更改 
我可以提供相关的链接 您看可以帮助我改造一下你的现在的项目对于我学校的适配吗   
![image](https://github.com/user-attachments/assets/a8bdebb9-293f-4647-8494-f2b204b17db1)

**Comment by bear-zd** [comment]
我之前尝试过有些学校的套皮版本，因为是基于学校的网站集成的学习通，因此不可避免的得实现一下学校的登录（login函数），这个还是自己想办法实现一下吧，实现好之后修改一下预约的url应该就好了

**Comment by itmanmax** [comment]
我现在借助gpt分析我的抓包数据实现了可以登录 其他的情况可以帮我修改一下吗？

**Comment by itmanmax** [comment]
![image](https://github.com/user-attachments/assets/c34a7d49-60d0-4628-bd27-68896badeb06)
![Uploading image.png…]()

**Comment by itmanmax** [comment]
实在是看不出来要处理哪些部分了作者大大

**Comment by itmanmax** [comment]
给您点米帮助我一下好吗，作者大大

**Comment by bear-zd** [comment]
可能还有两个要改的地方：
1、学习通URL用的是（reserve.py）
```python
self.url = "https://office.chaoxing.com/front/third/apps/seat/code?id={}&seatNum={}"
self.submit_url = "https://office.chaoxing.com/data/apps/seat/submit"
self.seat_url = "https://office.chaoxing.com/data/apps/seat/getusedtimes"
self.login_url = "https://passport2.chaoxing.com/fanyalogin"
```
你可能得视情况把self.url前缀修改，self.submit_url修改一下
2、我看页面token没有获取成功，这个token是根据self.url填入seatid和seatnum之后对页面解析得到的，可能修改self.url就可以解决，也有可能需要自己抓包解析一下微信

给米就算了 如果修改麻烦的话可以加vx我会回复快一点
