### ISSUE TITLE
{'msg': '预约失败，请退出后重试！', 'success': False}

### ISSUE THREAD

**Issue by tongxil** [bear-zd/ChaoXingReserveSeat#7]
您好，我是个github新手，我用github action部署的方式使用，但出现了下面这个问题，也核对了roomid和seatId，请问怎么解决
{'roomId': '4531', 'day': '2024-03-08', 'startTime': '19:00', 'endTime': '22:30', 'seatNum': '011', 'token': '', 'captcha': '', 'type': 1, 'verifyData': 1, 'enc': 'ba75ea869aa742c519df3ade1f80bea7'}
{'msg': '预约失败，请退出后重试！', 'success': False}

**Comment by bear-zd** [comment]
我这边重新测试无误，可以查看是否填写内容有误

**Comment by bear-zd** [comment]
这个确实不是代码能解决的。1988110c1419e85c69c00ce72aa0714707b4c75a
